### ISSUE TITLE
Vulnerability in sequelize 1.7.0-rc9 of cfpb/click-to-comment

### ISSUE THREAD

**Issue by curphey** [cfpb/click-to-comment#20]
Your **sequelize 1.7.0-rc9** library, a direct dependency in your **cfpb/click-to-comment** repository, is subject to vulnerability [SID-1458: SQL Injection](https://www.sourceclear.com/registry/vulnerabilities/1458).

A direct dependency is a library that is specified in your project’s package.json.  A vulnerability in a direct dependency can be fixed by updating the version of the library in your project and rebuilding it.

This issue was fixed in version 2.0.0-rc8. However, that version may itself be subject to [other vulnerabilities](https://www.sourceclear.com/registry/libraries/695?version=2.0.0-rc8). We suggest that you upgrade to version 3.24.0, which is considered safe.

Applying the fix may break your project, so we recommend that you always build and test your project to verify that the fix has been successful.

##### package.json
```js
"dependencies": {
  ...,
  "sequelize": "3.24.0",
  ...,
}
```

For more information on this vulnerability, please visit the [SourceClear Registry](https://www.sourceclear.com/registry/vulnerabilities/1458).

**Comment by curphey** [comment]
Any update on this ?

**Comment by ascott1** [comment]
Hi @curphey thank you for bringing this to our attention! This is a deprecated experimental project that is not being used in production. I've marked the repo as deprecated so that those outside of our organization are made aware of its status.

That said, we'll either update the dependencies or remove this repository from GitHub.

Thank you again!

**Comment by curphey** [comment]
Thanks!
